name: Release GitHub Releases
on:
  workflow_call:
    inputs:
      level:
        type: string
        required: true
        description: Bump up to [patch / minor / major]

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Bump Version
        id: bump
        uses: tmknom/bump-version-action@87bed7f224292cab5b46a4cae9897bbf64153f00 # v0.2.1
        with:
          bump-level: ${{ inputs.level }}

      - name: Push Version Tag
        uses: tmknom/push-version-tag-action@a9d1b46f9c29d3db510771452257b228bfd8a33f # v0.1.1
        with:
          version: ${{ steps.bump.outputs.version }}

      - name: Release
        env:
          VERSION: ${{ steps.bump.outputs.version }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
